# docker-compose.yml CORRIGIDO

services:
  n8n:
    image: n8nio/n8n:latest 
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio
      - WEBHOOK_URL=http://localhost:5678